/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  category: CategoryReference;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price: number;
  compareAtPrice?: number;
  material?: string;
  variants: Array<{
    size?: string;
    color?: string;
    sku: string;
    stock: number;
    _type: "variant";
    _key: string;
  }>;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  department: "clothes" | "shoes" | "jewelry" | "accessories";
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CategoryReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug,    department,    image  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  department: "accessories" | "clothes" | "jewelry" | "shoes";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_DEPARTMENT_QUERY
// Query: *[_type == "product" && category->department == $department] | order(name asc) {    _id,    name,    slug,    price,    compareAtPrice,    images,    featured,    "category": category->{title, slug}  }
export type PRODUCTS_BY_DEPARTMENT_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  featured: boolean | null;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && featured == true] | order(_createdAt desc) [0...8] {    _id,    name,    slug,    price,    compareAtPrice,    images,    "category": category->{title, slug}  }
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {    _id,    name,    slug,    description,    price,    compareAtPrice,    material,    images,    variants,    "category": category->{title, slug, department}  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  description: string | null;
  price: number;
  compareAtPrice: number | null;
  material: string | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  variants: Array<{
    size?: string;
    color?: string;
    sku: string;
    stock: number;
    _type: "variant";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
    department: "accessories" | "clothes" | "jewelry" | "shoes";
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_DEPARTMENT_NEWEST_QUERY
// Query: *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(_createdAt desc) [$start...$end] {  _id,  name,  slug,  price,  compareAtPrice,  images,  "category": category->{title, slug}}
export type PRODUCTS_BY_DEPARTMENT_NEWEST_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_DEPARTMENT_PRICE_ASC_QUERY
// Query: *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(price asc) [$start...$end] {  _id,  name,  slug,  price,  compareAtPrice,  images,  "category": category->{title, slug}}
export type PRODUCTS_BY_DEPARTMENT_PRICE_ASC_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_DEPARTMENT_PRICE_DESC_QUERY
// Query: *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(price desc) [$start...$end] {  _id,  name,  slug,  price,  compareAtPrice,  images,  "category": category->{title, slug}}
export type PRODUCTS_BY_DEPARTMENT_PRICE_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_DEPARTMENT_COUNT_QUERY
// Query: count(*[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)])
export type PRODUCTS_BY_DEPARTMENT_COUNT_QUERY_RESULT = number;

// Source: sanity/lib/queries.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && category->department == $department && _id != $excludeId] | order(_createdAt desc) [0...4] {  _id,  name,  slug,  price,  compareAtPrice,  images,  "category": category->{title, slug}}
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[_type == "product" && (name match $term + "*" || description match $term + "*")] | order(name asc) {  _id,  name,  slug,  price,  compareAtPrice,  images,  "category": category->{title, slug}}
export type SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  price: number;
  compareAtPrice: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: {
    title: string;
    slug: Slug;
  };
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    department,\n    image\n  }\n': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "product" && category->department == $department] | order(name asc) {\n    _id,\n    name,\n    slug,\n    price,\n    compareAtPrice,\n    images,\n    featured,\n    "category": category->{title, slug}\n  }\n': PRODUCTS_BY_DEPARTMENT_QUERY_RESULT;
    '\n  *[_type == "product" && featured == true] | order(_createdAt desc) [0...8] {\n    _id,\n    name,\n    slug,\n    price,\n    compareAtPrice,\n    images,\n    "category": category->{title, slug}\n  }\n': FEATURED_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    description,\n    price,\n    compareAtPrice,\n    material,\n    images,\n    variants,\n    "category": category->{title, slug, department}\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(_createdAt desc) [$start...$end] {\n  _id,\n  name,\n  slug,\n  price,\n  compareAtPrice,\n  images,\n  "category": category->{title, slug}\n}\n': PRODUCTS_BY_DEPARTMENT_NEWEST_QUERY_RESULT;
    '\n  *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(price asc) [$start...$end] {\n  _id,\n  name,\n  slug,\n  price,\n  compareAtPrice,\n  images,\n  "category": category->{title, slug}\n}\n': PRODUCTS_BY_DEPARTMENT_PRICE_ASC_QUERY_RESULT;
    '\n  *[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)] | order(price desc) [$start...$end] {\n  _id,\n  name,\n  slug,\n  price,\n  compareAtPrice,\n  images,\n  "category": category->{title, slug}\n}\n': PRODUCTS_BY_DEPARTMENT_PRICE_DESC_QUERY_RESULT;
    '\n  count(*[_type == "product" && category->department == $department && ($categorySlug == "" || category->slug.current == $categorySlug)])\n': PRODUCTS_BY_DEPARTMENT_COUNT_QUERY_RESULT;
    '\n  *[_type == "product" && category->department == $department && _id != $excludeId] | order(_createdAt desc) [0...4] {\n  _id,\n  name,\n  slug,\n  price,\n  compareAtPrice,\n  images,\n  "category": category->{title, slug}\n}\n': RELATED_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && (name match $term + "*" || description match $term + "*")] | order(name asc) {\n  _id,\n  name,\n  slug,\n  price,\n  compareAtPrice,\n  images,\n  "category": category->{title, slug}\n}\n': SEARCH_PRODUCTS_QUERY_RESULT;
  }
}
